apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
 name: full-stack-user
 description: REST API for managing users in the system
 annotations:
 github.com/project-slug: user-29
spec:
 type: service
 owner: guest
 lifecycle: production
